### ISSUE TITLE
Mekanism/Nether Ores problem

### ISSUE THREAD

**Issue by cloakable** [buttilda/Another-One-Bites-the-Dust#101]
Running AOBD 2.8.4, Mekanism 8.1.7.252, and Nether Ores 2.3.9-12.

Mekanism and Nether Ores are enabled in AOBD, but are not accepted in the Enrichment Chamber, Purification Chamber, nor the factory versions. It's working for Tinkers Construct, Thermal Foundation, and Big Reactors ores though.

**Comment by buttilda** [comment]
Turn the nether ores into normal ores (by smelting them iirc), and then process those ores as usual.

**Comment by cloakable** [comment]
That's what I'm doing, it's just messing up my automated processing chain (ender chest-> purification factory->crushing factory->enrichment factory->smelting factory), so wanted to point it out.

**Comment by buttilda** [comment]
It works for those mods because they probably add support for NetherOres natively.
The only support AOBD adds with NetherOres it the ability to turn them into ordinary ores.

I can look into add support for Mekanism. What would you suggest?

**Comment by buttilda** [comment]
Closing due to lack of response.
