### ISSUE TITLE
Texture Issue Reactorcraft

### ISSUE THREAD

**Issue by yosomith** [buttilda/Another-One-Bites-the-Dust#105]
There is currently a texture issue with Reactorcraft Cadmium, Indium and Thorium where I get black textures instead. The items are fine and no crashes, just black textures. 

Here is a screenshot of what I mean
![2015-10-26_10 17 23](https://cloud.githubusercontent.com/assets/4263201/10718589/f4542cee-7bca-11e5-8169-44dd87b007fe.png)

Also forge log if needed
https://www.dropbox.com/s/4atkunva6mlaovz/fml-client-latest.log?dl=0

**Comment by buttilda** [comment]
The textures aren't black, those metals just have their colours set to black in the config file. Just change the colour value in the file and it will work.

Deleting the file and letting AOBD generate a new one might also work.
