### ISSUE TITLE
Please remove the code that throws exceptions.

### ISSUE THREAD

**Issue by huanghongxun** [buttilda/Another-One-Bites-the-Dust#106]
I found that your mod will throw RuntimeException if a item(not ItemBlock) registered in the ore dictionary with prefix "block" in "TinkersConstruct.java:45".
Could you remove that behavior?

**Comment by buttilda** [comment]
Why?

**Comment by huanghongxun** [comment]
just caused my mod crashing.
Could you continue it instead of crashing?

**Comment by buttilda** [comment]
No because I didn't add that there just for the sake of it. AOBD can't continue if it hasn't found a block that has an item block associated with it. Tinker's Construct needs one for its recipes.

Also, why are you creating a block that doesn't have an ItemBlock?

**Comment by buttilda** [comment]
Closing due to lack of response.
