### ISSUE TITLE
Buckets for molten fluids in TC?

### ISSUE THREAD

**Issue by tgstyle** [buttilda/Another-One-Bites-the-Dust#110]
Some mods use a fluid bucket for fluid filters, it would be nice to utilize these features for fluids created by AOBD.

**Comment by buttilda** [comment]
Sure!
I'll make it cans, because for buckets I'd need to make the fluids placeable in world, and that's just pointless in my opinion.
The cans will be registered as fluid containers, so they should work as filters.

Thanks for the suggestion :D

**Comment by UndeadZeratul** [comment]
Why not bottles?  Then you can leverage an existing item, instead of making a custom one just for the sake of having a fluid container.

**Comment by buttilda** [comment]
Because there's only a handful of molten metals that a glass bottle would hold.
Although cans/buckets probably wouldn't hold much either...

**Comment by UndeadZeratul** [comment]
~~Yeah, true; but couldn't the same be said about an iron bucket?  Aren't there molten metals hotter than iron?~~

Just saw you mentioned buckets, ignore me.

**Comment by buttilda** [comment]
Yeah makes sense. Might as well use a bottle :3

**Comment by tgstyle** [comment]
One mod that you may want to test with is EnderIO Fluid Condiuits, they use fluid filters.

**Comment by buttilda** [comment]
Do they? How do I use filters on them?
I tried right-clicking with the wrench but it only gives me the option to change the mode (extract/insert/etc) and redstone controls

**Comment by tgstyle** [comment]
Try a Ender Fluid Conduit

**Comment by buttilda** [comment]
Oh that one works :3
Everything is done, but it seems like EnderIO is not handling fluids the way it should. I've reported the issue to them here: https://github.com/SleepyTrousers/EnderIO/issues/3005

**Comment by tgstyle** [comment]
Awesome! Thanks!
