### ISSUE TITLE
Crash with magneticraft

### ISSUE THREAD

**Issue by catzs** [buttilda/Another-One-Bites-the-Dust#111]
https://github.com/cout970/Magneticraft-API-and-Issues/issues/20

**Comment by buttilda** [comment]
It's the third time he's changed his API ಠ_ಠ
I'll fix it, thanks for letting me know :3

**Comment by buttilda** [comment]
So I looked into Magneticraft's latest releases and turns out they didn't actually change the API.

You're either using an old version of AOBD or an old version of Magneticraft. Update to the latest of both and it will work!
