### ISSUE TITLE
Metallurgy Ores arent working in Rotarycraft extractor

### ISSUE THREAD

**Issue by BakermanLP** [buttilda/Another-One-Bites-the-Dust#114]
The ores of Metallurgy don't work in the extractor of rotarycraft. In the grinder they work. The recipes are displayed as working, but the ore can't be placed in the extractor.

The config contains:
...
B:RotaryCraft=true
...
Used versions:
- AOBD-2.8.4.jar
- DragonAPI 1.7.10 V10c.jar
- RotaryCraft 1.7.10 V10b.jar

More information and configs can be found here:
https://github.com/BakermanLP/ProjectRETv8

**Comment by buttilda** [comment]
The support for RotaryCraft never worked and is still broken. Reika and I still have no idea why, so it remains an open issue (as you can see here #72)

**Comment by buttilda** [comment]
Closing this so the discussion stays in a single issue :)
