### ISSUE TITLE
With RotaryCraft v14, Server crash

### ISSUE THREAD

**Issue by pikkon38** [buttilda/Another-One-Bites-the-Dust#125]
When adding RotaryCraft v14, there seems to be an issue with aobd. I am not sure if this is an aobd mod or a RC mod, as the crash log references both.

[crash-2016-06-01_19.48.17-server.txt](https://github.com/ganymedes01/Another-One-Bites-the-Dust/files/294742/crash-2016-06-01_19.48.17-server.txt)

**Comment by decrobyron** [comment]
Same issue here.

**Comment by ReikaKalseki** [comment]
See https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/902

**Comment by ReikaKalseki** [comment]
I am getting this reported 20+ times a day...

**Comment by pikkon38** [comment]
The workaround for this is to turn all RotaryCraft support off in the AOBD config file. Change all isntances of "B:RotaryCraft=true" to "B:RotaryCraft=false". Reika does a good job of supporting many different ores from many mods. So changing this to false really wont hurt much of anything in terms of gameplay.

**Comment by Baughn** [comment]
How can this even happen? Near as I can see, the method _still exists_, Reika just changed the return type. From void.

I'm probably missing something obvious.

**Comment by ReikaKalseki** [comment]
The return type is part of the method.

`Reika.RotaryCraft.API.ExtractAPI.addCustomExtractEntry(Ljava/lang/String;LReika/DragonAPI/Interfaces/Registry/OreType$OreRarity;Ljava/lang/String;Ljava/lang/String;IIILReika/DragonAPI/Interfaces/Registry/OreType;[Ljava/lang/String;)[Return]`

`addCustomExtractEntry(String, OreRarity, String, String, int, int, int, OreType, String)[Return]`
