### ISSUE TITLE
 Mod is dead now?

### ISSUE THREAD

**Issue by mgdgfbhevdyeh** [buttilda/Another-One-Bites-the-Dust#132]
looks modder is gone.

**Comment by buttilda** [comment]
pretty much )= No more time for modding </3

**Comment by mgdgfbhevdyeh** [comment]
@ganymedes01 Glad to see you here:)
Mod can temporarily stop the development, but as with most players, hope Mod not to die
I wish you a speedy time<3

Edit:sorry for my English
