### ISSUE TITLE
Feature request: Steel dust

### ISSUE THREAD

**Issue by kieranmenor** [buttilda/Another-One-Bites-the-Dust#21]
NetherOres adds Pig Iron Ore, which is a steel ore. A couple of mods have steel ingots, but no mods add dust. I think Universal Electricity used to have a suitable dustSteel, but it doesn't seem to anymore, at least.

So yeah, please consider adding steel dust.

**Comment by buttilda** [comment]
AOBD will automatically add steel dust if it finds oreSteel and ingotSteel in any of the mods you have installed.
I don't add anything manually.

**Comment by kieranmenor** [comment]
Well, NetherOres' Pig Iron Ore registers as oreNetherSteel, but not oreSteel.

**Comment by kieranmenor** [comment]
... So, perhaps a way to detect nether ores or maybe the ability to force enable a dust?

**Comment by buttilda** [comment]
The author of Nether Ores probably does that to differentiate his ores from normal ores.
Which means he doesn't want his ores being processed the same way as others.
If he wanted his nether ores to be treated just like other ores, then he could simply register them like everyone else does (oreSteel in this case).

Talk to the dev of NetherOres, and ask him to register his ores in the standard way IF no ores registered in the standard way are found (e.g. register oreNetherSteel as oreSteel if no oreSteel is found)

Another option would be to use a mod that allows you to customise the game (like ZZZZZCustomConfigs or MineTweaker) and register the pig iron ore as oreSteel yourself.

**Comment by buttilda** [comment]
Feel free to link this issue to the author and invite him for a discussion if you think that would be necessary.

**Comment by kieranmenor** [comment]
As far as I can gather, NetherOres works sort of opposite of this mod: adding nether ores where a dust exists. Nether ores generally have a higher yield (double in most cases) than their regular counter parts, which might be the difference you describe. Registering Pig Iron Ore as oreSteel with MineTweaker might work, but I'm not sure what effects it will have on the yield when processed in that case.

**Comment by skyboy** [comment]
NetherOres works in a similar fashion to this, and adds ores for worldgen when an ore, ingot, dust, or some alternative entry (ore-specific) is found; with the ores registered as oreNether[Value] so it can be detected, but avoids regular ore processing mechanics since it smelts into 2 standard ores, or otherwise generally results in double the output of a standard ore.

**Comment by kieranmenor** [comment]
Oh, well now I feel like a fool. Sorry, didn't see you had commented already. >_>

**Comment by buttilda** [comment]
So there's no point into wanting to register oreNetherSteel as oreSteel just so you can double it if it already smelts into two ingots...

**Comment by kieranmenor** [comment]
It doesn't smelt into two ingots - it would smelt into two ores. No actual oreSteel exists, though, so back in the day, it would work because UE added the steel dust. I think you can smelt it in the TiC smeltery, as well.

**Comment by buttilda** [comment]
What does it smelt into then?

**Comment by kieranmenor** [comment]
The nether ore will smelt into oreX if such an ore exists, and/or pulverize/macerate/etc. into dustX if such a dust exists. If neither are registered, the ore will not generate.

**Comment by buttilda** [comment]
I think I can add compatibility with NetherOres then, I'll have AOBD check if oreNetherX and ingotX are present, and if so, automatically generate the oreX items (just items, they won't generate anywhere) and those will then be processable by other mods...
No promises though, it's just a thought, I don't know how well it will work

**Comment by kieranmenor** [comment]
Seems like a good solution.
