### ISSUE TITLE
Crashes upon startup of forge-1.7.10-10.13.2.1240 Server

### ISSUE THREAD

**Issue by MichibuenKosai** [buttilda/Another-One-Bites-the-Dust#23]
AOBD-2.3.2: Crashes upon startup of forge-1.7.10-10.13.2.1240 Server.

Works when reverted to AOBD-2.3.1

---- Minecraft Crash Report ----
Time: 11/30/14 5:37 AM
Description: Exception in server tick loop

cpw.mods.fml.common.LoaderException: java.lang.NoSuchFieldError: hasEffect
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:162)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:692)
    at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97)
    at cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:319)
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:210)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.NoSuchFieldError: hasEffect
    at ganymedes01.aobd.items.AOBDItem.<init>(AOBDItem.java:21)
    at ganymedes01.aobd.ore.OreFinder.generateItems(OreFinder.java:87)
    at ganymedes01.aobd.ore.OreFinder.init(OreFinder.java:64)
    at ganymedes01.aobd.AOBD.init(AOBD.java:69)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:691)
    ... 5 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Linux (amd64) version 3.13.0-39-generic
    Java Version: 1.7.0_72, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1432203072 bytes (1365 MB) / 2473066496 bytes (2358 MB) up to 3817865216 bytes (3641 MB)
    JVM Flags: 3 total; -Xms2048M -Xmx4096M -XX:PermSize=128M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.85.1240 Minecraft Forge 10.13.2.1240 152 mods loaded, 152 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    FML{7.10.85.1240} [Forge Mod Loader](forge-1.7.10-10.13.2.1240-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Forge{10.13.2.1240} [Minecraft Forge](forge-1.7.10-10.13.2.1240-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    appliedenergistics2-core{rv2-alpha-26} [AppliedEnergistics2 Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    CodeChickenCore{1.0.4.29} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    <CoFH ASM>{000} [CoFH ASM Data Initialization](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    InfiniBows{1.3.0 build 20} [InfiniBows](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MobiusCore{1.2.3} [MobiusCore](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    NotEnoughItems{1.0.3.68} [Not Enough Items](NotEnoughItems-1.7.10-1.0.3.68-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    OpenComputers|Core{1.0.0} [OpenComputers (Core)](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    OpenModsCore{@VERSION@} [OpenModsCore](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    debug{1.0} [debug](denseores-1.5.jar) Unloaded->Constructed->Pre-initialized->Initialized
    act{0.0.2a_1.7.10} [AdminCommandsToolbox](AdminCommandsToolbox-0.0.2a_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
    AppleCore{1.0.1} [AppleCore](AppleCore-mc1.7.10-1.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    appliedenergistics2{rv2-alpha-26} [Applied Energistics 2](appliedenergistics2-rv2-alpha-26.jar) Unloaded->Constructed->Pre-initialized->Initialized
    CoFHCore{1.7.10R3.0.0B8} [CoFH Core](CoFHCore-[1.7.10]3.0.0B8-36.jar) Unloaded->Constructed->Pre-initialized->Initialized
    autopackager{1.5.2} [AutoPackager](autopackager-1.5.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BiblioCraft{1.9.1} [BiblioCraft](BiblioCraft[v1.9.1][MC1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized
    Mantle{1.7.10-0.3.2.jenkins184} [Mantle](Mantle-1.7.10-0.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Natura{2.2.0} [Natura](natura-1.7.10-2.2.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BiomesOPlenty{2.1.0} [Biomes O' Plenty](BiomesOPlenty-1.7.10-2.1.0.1019-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BiblioWoodsBoP{1.9} [BiblioWoods Biomes O'Plenty Edition](BiblioWoods[BiomesOPlenty][v1.9].jar) Unloaded->Constructed->Pre-initialized->Initialized
    BuildCraft|Core{6.2.0} [BuildCraft](buildcraft-6.2.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Forestry{3.1.1.4} [Forestry for Minecraft](forestry_1.7.10-3.1.1.4.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BiblioWoodsForestry{1.7} [BiblioWoods Forestry Edition](BiblioWoods[Forestry][v1.7].jar) Unloaded->Constructed->Pre-initialized->Initialized
    BiblioWoodsNatura{1.5} [BiblioWoods Natura Edition](BiblioWoods[Natura][v1.5].jar) Unloaded->Constructed->Pre-initialized->Initialized
    ThermalFoundation{1.7.10R1.0.0B3} [Thermal Foundation](ThermalFoundation-[1.7.10]1.0.0B3-8.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ThermalExpansion{1.7.10R4.0.0B6} [Thermal Expansion](ThermalExpansion-[1.7.10]4.0.0B6-16.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BigReactors{0.4.0rc8} [Big Reactors](BigReactors-0.4.0rc8.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BinnieCore{2.0-dev5} [Binnie Core](binnie-mods-2.0-dev5.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Botany{2.0-dev5} [Botany](binnie-mods-2.0-dev5.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ExtraBees{2.0-dev5} [Extra Bees](binnie-mods-2.0-dev5.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ExtraTrees{2.0-dev5} [Extra Trees](binnie-mods-2.0-dev5.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Genetics{2.0-dev5} [Genetics](binnie-mods-2.0-dev5.jar) Unloaded->Constructed->Pre-initialized->Initialized
    AWWayofTime{v1.2.1b} [Blood Magic: Alchemical Wizardry](BloodMagic-1.7.10-1.2.1b-1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Baubles{1.0.1.9} [Baubles](Baubles-1.7.10-1.0.1.9.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Thaumcraft{4.2.1.4} [Thaumcraft](Thaumcraft-1.7.10-4.2.1.4.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Botania{r1.3-138} [Botania](Botania r1.3-138.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BuildCraft|Transport{6.2.0} [BC Transport](buildcraft-6.2.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BuildCraft|Silicon{6.2.0} [BC Silicon](buildcraft-6.2.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BuildCraft|Builders{6.2.0} [BC Builders](buildcraft-6.2.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BuildCraft|Energy{6.2.0} [BC Energy](buildcraft-6.2.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BuildCraft|Factory{6.2.0} [BC Factory](buildcraft-6.2.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
    eureka{2.1} [Eureka](Eureka-1.7.10-2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    bcadditions{1.8.1} [Buildcraft Additions](BuildcraftAdditions-1.7.10-1.8.1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    CarpentersBlocks{3.3.3} [Carpenter's Blocks](Carpenter's Blocks v3.3.3 - MC 1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ChickenChunks{1.3.4.14} [ChickenChunks](ChickenChunks-1.7.10-1.3.4.14-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ForgeMultipart{1.1.0.314} [Forge Multipart](ForgeMultipart-1.7.10-1.1.0.314-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    chisel{2.1.0.0} [Chisel](Chisel 2-2.1.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ChiselFacades{1.7.10-2.4-cricket} [Chisel Facades](ChiselFacades-1.7.10-2.4-cricket.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ComputerCraft{1.65} [ComputerCraft](ComputerCraft1.65.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Dynmap{2.0.0-61} [Dynmap](Dynmap-2.0.0-forge-10.13.0.SERVERONLY.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded{1.7.10R2.8.0RC5} [MineFactory Reloaded](MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized->Initialized
    EnderIO{1.7.10-2.2.1.276} [Ender IO](EnderIO-1.7.10-2.2.1.276.jar) Unloaded->Constructed->Pre-initialized->Initialized
    EnderStorage{1.4.5.25} [EnderStorage](EnderStorage-1.7.10-1.4.5.25-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    EE3{0.2.369} [Equivalent Exchange 3](EquivalentExchange3-1.7.10-0.2.369.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Waila{1.5.5} [Waila](Waila-1.5.5_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
    TConstruct{1.7.10-1.7.1.build771} [Tinkers' Construct](TConstruct-1.7.10-1.7.1c.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ExtraTiC{0.8.4} [ExtraTiC](ExtraTiC-1.7.10-1.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ExtraUtilities{1.2.0} [Extra Utilities](extrautilities-1.2.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
    factorization.notify{1.0} [Factorization Notification System](Factorization-1.7.10-0.8.88.7.jar) Unloaded->Constructed->Pre-initialized->Initialized
    factorization{1.7.10-0.8.88.7} [Factorization](Factorization-1.7.10-0.8.88.7.jar) Unloaded->Constructed->Pre-initialized->Initialized
    factorization.misc{1.7.10-0.8.88.7} [Factorization Miscellaneous Nonsense](Factorization-1.7.10-0.8.88.7.jar) Unloaded->Constructed->Pre-initialized->Initialized
    FastCraft{1.9} [FastCraft](fastcraft-1.9.jar) Unloaded->Constructed->Pre-initialized->Initialized
    FlatSigns{2.1.0.19} [Flat Signs](FlatSigns-1.7.10-universal-2.1.0.19.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ThaumicTinkerer{unspecified} [Thaumic Tinkerer](ThaumicTinkerer-2.5-1.7.10-161.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ForbiddenMagic{1.7.10-0.55} [Forbidden Magic](Forbidden Magic-1.7.10-0.55.jar) Unloaded->Constructed->Pre-initialized->Initialized
    funkylocomotion{1.0} [Funky Locomotion](funky-locomotion-1.7.10-beta-2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    HelpFixer{1.0.3} [HelpFixer](HelpFixer-1.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized
    harvestcraft{1.7.10b} [Pam's HarvestCraft](Pam's HarvestCraft 1.7.10c.jar) Unloaded->Constructed->Pre-initialized->Initialized
    HungerOverhaul{1.7.10-beta.2.jenkins30} [Hunger Overhaul](HungerOverhaul-1.7.10-beta.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    iChunUtil{4.1.2} [iChunUtil](iChunUtil-4.1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ImLookingAtBlood{1.1} [I'm Looking At Blood](ImLookingAtBlood-1.7.2-1.1a.jar) Unloaded->Constructed->Pre-initialized->Initialized
    inpure|core{1.7.10R1.0.0B7} [INpureCore](INpureCore-[1.7.10]1.0.0B7-19.jar) Unloaded->Constructed->Pre-initialized->Initialized
    inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks](InventoryTweaks-1.59-dev-152.jar) Unloaded->Constructed->Pre-initialized->Initialized
    IronChest{6.0.62.742} [Iron Chest](ironchest-1.7.10-6.0.62.742-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    JABBA{1.1.4} [JABBA](Jabba-1.1.4_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
    JourneyMapServer{1.0.0_Forge_Bukkit_MC1.7.10} [JourneyMapServer](JourneyMapServer1.0.0MC1.7.10.SERVERONLY.jar) Unloaded->Constructed->Pre-initialized->Initialized
    LogisticsPipes{0.8.2.83} [Logistics Pipes](logisticspipes-0.8.2.83.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MagicBees{1.7.10-2.1.22} [Magic Bees](magicbees-1.7.10-2.1.22.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0RC5} [MFR Compat: Applied Energistics](MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatAtum{1.7.10R2.8.0RC4} [MFR Compat: Atum](MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0RC5} [MFR Compat: BackTools](MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0RC4} [MFR Compat: BuildCraft](MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0RC4} [MFR Compat: Chococraft](MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0RC4} [MFR Compat: ExtraBiomes](MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatForestry{1.7.10R2.8.0RC5} [MFR Compat: Forestry](MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0RC4} [MFR Compat: ForgeMicroblock](MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatIC2{1.7.10R2.8.0RC4} [MFR Compat: IC2](MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Mystcraft{0.11.0.00} [Mystcraft](mystcraft-1.7.10-0.11.0.00.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0RC4} [MFR Compat: Mystcraft](MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MrTJPCoreMod{1.0} [MrTJPCoreMod](MrTJPCore-1.7.10-1.0.3.5-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ProjRed|Core{4.5.7.58} [ProjectRed](ProjectRed-1.7.10-4.5.7.58-Base.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0RC4} [MFR Compat ProjectRed](MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0RC4} [MFR Compat: Railcraft](MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatRP2{1.7.10R2.8.0RC4} [MFR Compat: RP2](MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0RC4} [MFR Compat: Sufficient Biomes](MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0RC5} [MFR Compat: Thaumcraft](MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0RC4} [MFR Compat: Thermal Expansion](MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized->Initialized
    TwilightForest{2.3.2} [The Twilight Forest](twilightforest-1.7.10-2.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0RC5} [MFR Compat: TwilightForest](MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0RC5} [MFR Compat: Vanilla](MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineMenu{1.2.0} [MineMenu](MineMenu-1.7.10-1.2.0.B44-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineTweaker3{3.0.9} [MineTweaker 3](MineTweaker3-1.7.10-3.0.9.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Morph{0.9.1} [Morph](Morph-Beta-0.9.1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    NEIAddons{1.12.3.11} [NEI Addons](neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized->Initialized
    NEIAddons|Botany{1.12.3.11} [NEI Addons: Botany](neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized->Initialized
    NEIAddons|Forestry{1.12.3.11} [NEI Addons: Forestry](neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized->Initialized
    NEIAddons|CraftingTables{1.12.3.11} [NEI Addons: Crafting Tables](neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized->Initialized
    NEIAddons|ExNihilo{1.12.3.11} [NEI Addons: Ex Nihilo](neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized->Initialized
    neiintegration{1.0.1} [NEI Integration](NEIIntegration-MC1.7.10-1.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    NetherOres{1.7.10R2.3.0RC3} [Nether Ores](NetherOres-[1.7.10]2.3.0RC3-84.jar) Unloaded->Constructed->Pre-initialized->Initialized
    NotEnoughCodecs{0.3} [NotEnoughCodecs](NotEnoughCodecs-1.7.10-0.3-snapshot-11.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ObsidiPlates{3.0.0.18} [ObsidiPlates](ObsidiPlates-1.7.10-universal-3.0.0.18.jar) Unloaded->Constructed->Pre-initialized->Initialized
    OpenMods{0.6} [OpenMods](OpenModsLib-1.7.10-0.6-snapshot-224.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ProjRed|Transmission{4.5.7.58} [ProjectRed-Transmission](ProjectRed-1.7.10-4.5.7.58-Integration.jar) Unloaded->Constructed->Pre-initialized->Initialized
    OpenPeripheralCore{0.5.0} [OpenPeripheralCore](OpenPeripheralCore-1.7.10-0.5.0-snapshot-142.jar) Unloaded->Constructed->Pre-initialized->Initialized
    OpenPeripheral{0.2.0} [OpenPeripheralAddons](OpenPeripheralAddons-1.7.10-0.2.0-snapshot-122.jar) Unloaded->Constructed->Pre-initialized->Initialized
    OpenBlocks{1.3} [OpenBlocks](OpenBlocks-1.7.10-1.3-snapshot-433.jar) Unloaded->Constructed->Pre-initialized->Initialized
    OpenComputers{1.4.1.14} [OpenComputers](OpenComputers-MC1.7.10-1.4.1.14-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Photoreal{4.0.0} [Photoreal](Photoreal-4.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
    PiP{4.0.0} [PiP](PiP-4.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ProjRed|Compatibility{4.5.7.58} [ProjectRed-Compatibility](ProjectRed-1.7.10-4.5.7.58-Compat.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ProjRed|Integration{4.5.7.58} [ProjectRed-Integration](ProjectRed-1.7.10-4.5.7.58-Integration.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ProjRed|Illumination{4.5.7.58} [ProjectRed-Illumination](ProjectRed-1.7.10-4.5.7.58-Lighting.jar) Unloaded->Constructed->Pre-initialized->Initialized
    YogpstopLib{2.0.0} [Yogpstop Library](QuarryPlus-1.7.10LBC-2.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
    QuarryPlus{2.0.0} [QuarryPlus](QuarryPlus-1.7.10LBC-2.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
    RedstoneArsenal{1.7.10R1.1.0RC1} [Redstone Arsenal](RedstoneArsenal-[1.7.10]1.1.0RC1-19.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Roguelike{1.3.5} [Roguelike Dungeons](roguelike-1.7.10-1.3.5.jar) Unloaded->Constructed->Pre-initialized->Initialized
    simplyjetpacks{1.2.0} [Simply Jetpacks](SimplyJetpacks-MC1.7.10-1.2.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
    SpiceOfLife{1.2.2} [The Spice of Life](SpiceOfLife-mc1.7.10-1.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    StevesFactoryManager{A93} [Steve's Factory Manager](StevesFactoryManagerA93.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Sync{4.0.0} [Sync](Sync-4.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
    thaumcraftneiplugin{1.7.10-1.6a} [Thaumcraft NEI Plugin](thaumcraftneiplugin-1.7.10-1.6a.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ThaumicExploration{0.6.0} [Thaumic Exploration](ThaumicExploration-1.7.10-1.1-31.jar) Unloaded->Constructed->Pre-initialized->Initialized
    TiCTooltips{1.1.11b} [TiC Tooltips](TiCTooltips-mc1.7.10-1.1.11b.jar) Unloaded->Constructed->Pre-initialized->Initialized
    TMechworks{1.7.10-86.e500b88} [Tinkers' Mechworks](TMechworks-1.7.10-0.2.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Translocator{1.1.1.13} [Translocator](Translocator-1.7.10-1.1.1.13-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    WailaHarvestability{1.1.0} [Waila Harvestability](WailaHarvestability-mc1.7.x-1.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
    wawla{1.0.9} [What Are We Looking At](Wawla-1.0.9_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
    witchery{0.20.6} [Witchery](witchery-1.7.10-0.20.6.jar) Unloaded->Constructed->Pre-initialized->Initialized
    worldedit{6.0-beta-01} [WorldEdit](worldedit-forge-mc1.7.10-6.0-beta-01.jar) Unloaded->Constructed->Pre-initialized->Initialized
    WR-CBE|Core{1.4.1.9} [WR-CBE Core](WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    WR-CBE|Addons{1.4.1.9} [WR-CBE Addons](WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    WR-CBE|Logic{1.4.1.9} [WR-CBE Logic](WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    bspkrsCore{6.15} [bspkrsCore]([1.7.10]bspkrsCore-universal-6.15.jar) Unloaded->Constructed->Pre-initialized->Initialized
    McMultipart{1.1.0.314} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.1.0.314-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    aobd{2.3.2} [Another One Bites The Dust](AOBD-2.3.2.jar) Unloaded->Constructed->Pre-initialized->Errored
    denseores{1.0} [Dense Ores](denseores-1.5.jar) Unloaded->Constructed->Pre-initialized->Initialized
    IguanaTweaksTConstruct{1.7.10-2.0.6} [Iguana Tinker Tweaks](IguanaTinkerTweaks-1.7.10-2.0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ForgeMicroblock{1.1.0.314} [Forge Microblocks](ForgeMultipart-1.7.10-1.1.0.314-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    AE2 Version: alpha rv2-alpha-26 for Forge 10.13.2.1230
    Mantle Environment: Environment healthy.
    TConstruct Environment: Environment healthy.
    Profiler Position: N/A (disabled)
    Is Modded: Definitely; Server brand changed to 'fml,forge'
    Type: Dedicated Server (map_server.txt)

**Comment by buttilda** [comment]
Already fixed. Thanks for reporting.
