### ISSUE TITLE
Hello! Mod Suggestion Idea

### ISSUE THREAD

**Issue by Lanse505** [buttilda/Another-One-Bites-the-Dust#25]
So i'm working on implementing a new iteration of worldgen For ResonantRise3 and i was wanting to implement IC2 Iridium Ore from AoBD into the worldgen using CoFH. However I noticed that you dont have a set AoBD base block that you assign your ore blocks to but instead you staticly generate the block during worldgen, is there anyway of getting a AoBD base block you assign your ore blocks too so I could get access to iridium for worldgen or this an impossible task :/. 

Thank you for taking ur time to look at this idea!

//Best Regards
Lanse

**Comment by buttilda** [comment]
AOBD doesn't have any blocks.
The ores you see are just items that render as blocks, you can't place them in the world or anything like that. They are generated just to allow NetherOres to be processed by other mod's machines that didn't specifically add compatibility with it.

If a mod has a iridium ore (as long as it's registered in the ore dictionary as oreIridium), AOBD will automatically use it instead of creating it's own.

**Comment by buttilda** [comment]
On a side note...
If all you want is a block of iridium ore, I can make a mod that adds just that in 5 minutes for you.
Since you'll use CoFHCore for handing the ore gen, I'm assuming all you'd really need is the block itself?

**Comment by Lanse505** [comment]
Yup, all i'll really need would be the Iridium ore block, then i could Minetweak/Modtweak in recipes for its uses :P

**Comment by buttilda** [comment]
Aweosme.
Do you know how to compile a mod with gradle?

**Comment by Lanse505** [comment]
Um not really, x.x i'm really bad at things like that ^^'. let me find someone useful in that department to acctually be useful at that department XD

**Comment by buttilda** [comment]
https://github.com/ganymedes01/IridiumMod

Your mod is ready sir ^^

**Comment by Lanse505** [comment]
Thank you Gany~ as a thanks you can get a sneakpeek on RR3 worldgen if u want ;3?

**Comment by buttilda** [comment]
Sure, I don't mind ^^
Tomorrow though, it's quite late. Me needs sleeps :3

Let me know if the mod works okay to you.
I added config options for hardness, blast resistance and mining level.
The texture is meh, made it in 2 minutes, so you might want to change it.

As for it working with AOBD...
AOBD will catch it if it also finds a ingotIridium registered in the ore dictionary and automatically generate all the items necessary to process the iridium in all the supported mods :)
I've heard that MineTweaker does it's ore dictionary registering quite late... so if you are registering a ingotIridium yourself using that mod, it probably won't work... Adding a Iridium Ingot to the mod I just made would solve the issue. I can do that for you as well if you need ^^

**Comment by Lanse505** [comment]
https://docs.google.com/spreadsheets/d/1_uO4YUeInnrwumw_4IC4WgldcbYsLKpuSbqa4cUJGDU/edit?usp=sharing There you go :), shoot me any thoughts and ideas you have. Btw you have an open invitation to join the RR-testing Teamspeak if you would like as a thanks for helping out ^^.

**Comment by Lanse505** [comment]
Hmm, an iridium ingot would be good to have acctually >.>.... god i feel like such a bother xD but yes i would love for an iridium ingot to be implemented into the iridium mod :3

**Comment by buttilda** [comment]
no worries, I enjoy helping XD

I can add the ingot, or I can make the the IridiumMod register IC2's iridium in the dictionary as ingotIridium, which one do you prefer?

Oh and should I add the smelting recipes ore -> ingot?

**Comment by buttilda** [comment]
Oh and the worldgen looks really nice ^^
I think it looks well distributed, and the spreadsheet looks really pretty lol XD

**Comment by Lanse505** [comment]
I perfer the Ic2 route seeing as that's why i was planning on implementing iridium into worldgen :P

**Comment by buttilda** [comment]
Done ^^

**Comment by buttilda** [comment]
Let me know if it causes any conflicts or anything like that. (I mean, they don't register it in the ore dictionary themselves, they are either just being annoying or there's a good reason for it...)

**Comment by Lanse505** [comment]
okey :P, thanks again Gany :) that invitation is open anytime :P

**Comment by buttilda** [comment]
maybe I'll jump on it later, I'm bit shy and have a chronic case of bad internet XD

**Comment by Lanse505** [comment]
It's Okey :P

**Comment by buttilda** [comment]
haha XD
What is it? I'm about to start a movie up, but I can work on it afterwards ^^

**Comment by Lanse505** [comment]
So apparently IC2 registers their iridium like IridiumOre, so its messing up with AOBD. Could we do a revision where we instead add a IridiumMod Iridium Ingot so that the Ore can acctually be refined with AOBD support?

**Comment by Lanse505** [comment]
Sorry for being such a hassle xP

**Comment by buttilda** [comment]
Sure no problem :3 That will be pretty simple to do.
But like I said, I'm about to watch a movie with friends, so I'll do it in a couple of hours :)

**Comment by Lanse505** [comment]
Its okey, no rush :P

**Comment by Lanse505** [comment]
Btw i'm suppost to tell you that my friend has a pull request on the iridium mod and he's going to make it so it auto-compiles the mod and puts it on a jenkins he made for me :)

**Comment by buttilda** [comment]
Added the ingot. Again, texture is pretty much a place holder. You should probably change it :)

As for the PR your friend sent, you can pull it yourself by clicking on the green button that says "merge pull request" on the bottom of the page: https://github.com/Lanse505/IridiumMod/pull/1

**Comment by Lanse505** [comment]
OH! i'm such a dunce x.x. Thanks alot Gany :)

**Comment by buttilda** [comment]
No problem :)
Feel free to ask if you need anything else done. This is pretty simple work, so it really doesn't bother me.

**Comment by Lanse505** [comment]
Gany you busy?

**Comment by buttilda** [comment]
Not at the moment :)
What's up?:3

**Comment by Lanse505** [comment]
wanna jump on our TS and help a fellow modder out (mod author of Fluxed Crops has some issues) that he cant figure out and frankly i'm the last person to ask about mod code ^^'

**Comment by Lanse505** [comment]
Or IRC would be better Jared is saying ^^

**Comment by Lanse505** [comment]
join IRC: #jaredlll08

**Comment by buttilda** [comment]
esper?

**Comment by Lanse505** [comment]
yes

**Comment by buttilda** [comment]
be there in 10mins or so :)

**Comment by buttilda** [comment]
I'm there :3
