### ISSUE TITLE
EnderIO Grinding is Unbalanced

### ISSUE THREAD

**Issue by ChatFawkes** [buttilda/Another-One-Bites-the-Dust#26]
When I have AOBD enabled in my modpack, mod ores such as: copper, tin, osmium, etc get grinded really fast in the EnderIO SAG Mill. Once I disable AOBD, the ores go back to grinding at their regular speed. This only seems to affect ores added by mods.

A solution to this is either removing AOBD or disabling EnderIO compat for all ores in the AOBD config.

AOBD Version: 2.3.5
EnderIO Version: 2.2.2.303

**Comment by ChatFawkes** [comment]
Seems like this might be the problem: https://github.com/ganymedes01/Another-One-Bites-the-Dust/blob/mc1.7/src/main/java/ganymedes01/aobd/recipes/modules/EnderIOModule.java#L32

Should be multiplied by 10 because EnderIO uses RF values now.

**Comment by buttilda** [comment]
Hm yeah that value was defined when MJ was still around.
Easy fix. I'll just multiply it by 10.
Thanks for reporting :)

**Comment by buttilda** [comment]
As a workaround you could just multiply the "energy" value in the config file by 10.
It will make the cost more expensive with other mods, but will fix it for EnderIO... so if you're only using EIO, that would be a decent enough fix until the next version :)

**Comment by ChatFawkes** [comment]
This is issue is still present when using AOBD 2.3.6 and EnderIO 2.2.6.322.

**Comment by buttilda** [comment]
Seems to be an EnderIO bug. No matter what energy value I tell it to use it keeps using 400RF.

Nvm, it was still my derp _sigh_
