### ISSUE TITLE
EnderIO recipe issues with Energy Costs/Speeds

### ISSUE THREAD

**Issue by Lanse505** [buttilda/Another-One-Bites-the-Dust#27]
TTerrag tells us through whispers in the wind that your calculating the energy required to process ores in MJ instead of RF for EnderIO machines which makes all Ores go through the SAG mill about 10x faster then their supposte to ^^.

**Comment by UndeadZeratul** [comment]
Should be fixed by d2bd8d4d7beb4f0faaf6428a281a37cd5d103176 as shown in https://github.com/ganymedes01/Another-One-Bites-the-Dust/issues/26

**Comment by Lanse505** [comment]
Okey, i'll tell Tterrag and the devs this ^^ thank you

**Comment by buttilda** [comment]
Yeah it's fixed already :)

**Comment by Lanse505** [comment]
Great :), then i'll inform the others a update is comeing :3
