### ISSUE TITLE
Minecraft version in mcmod.info

### ISSUE THREAD

**Issue by zlepper** [buttilda/Another-One-Bites-the-Dust#29]
Can this be added?
It would make some mod guessing I'm doing a bit easier.

**Comment by buttilda** [comment]
Send in the PR and I'll happily merge it :)

**Comment by zlepper** [comment]
I can't find your current mcmod.info file, so do you want me to create one from what there already is in the .jar file?

**Comment by buttilda** [comment]
https://github.com/ganymedes01/Another-One-Bites-the-Dust/blob/mc1.7/src/main/resources/mcmod.info
