### ISSUE TITLE
Add a way to translate the ore names

### ISSUE THREAD

**Issue by labpaw** [buttilda/Another-One-Bites-the-Dust#32]
It always stays in English -> http://i.imgur.com/x5ci02i.jpg

**Comment by buttilda** [comment]
Kind of hard to translate it since the ores are automatically detected. I have no idea what they'll be called.

**Comment by labpaw** [comment]
There are should be a workaround. These names looks really ugly because they mixed with two different languages. Maybe you can add most of supported names into .lang file?

**Comment by buttilda** [comment]
Then the least supported ones would look ugly XD
You can change the names for yourself using the config file ("In game name" config) but that's as far as I can go.

**Comment by labpaw** [comment]
As a translator, I want translate everything. And I can say you that leaving untranslated words in the middle of the string becomes superugly. Can you at least not closing this and make something like this in the future, not now?

**Comment by buttilda** [comment]
Okay, I'll leave it open, if someone comes up with a way to fix it I'll happily merge it.

**Comment by labpaw** [comment]
Ok, here it is. Check this: https://github.com/BCA-Team/Buildcraft-Additions/pull/296 This is an example of how to translate automatically detected stuff. Now you should just add it to AOBD. Additionally you should make it depend on "item type", so I should be able to add "item.dust(MaterialName).name", "item.crushed(MaterialName).name", "item.crushedPurified(MaterialName).name" etc.

**Comment by buttilda** [comment]
BCA doesn't have dynamically generated dusts...
What if AOBD runs into a metal that is not translated? Then we end up with "material.X.name Dust", which looks a lot worst than having the english name =/

**Comment by labpaw** [comment]
Dusts which added through OreDict not dynamic? But if AOBD runs into a metal that is not translated you should add fallback to old method. Check: https://github.com/TehNut/MoreChisels/commit/e3a59abcb5da6133332f108acd538a90de9b0b76 for more info.

**Comment by buttilda** [comment]
"StatCollector.canTranslate(String)"
If I also knew about this earlier my life would have been a lot easier XD Now I have a way of doing this safely :D

**Comment by buttilda** [comment]
Will implement it later when I get home :3

**Comment by labpaw** [comment]
Can you allow me to replace full name? So, instead of adding _DustName_ + "Dust", I can add "item.aobd.dustname.dust.name=_DustName_ Dust" if there are no "item.aobd.dustname.dust.name", _DustName_ + "Dust" should be used as default.
Additionally it should depend on "item type", I mean dust, ore, crushed, crushedPurified, dustTiny and etc.

**Comment by buttilda** [comment]
Wouldn't that make the lang files absolutely massive?

**Comment by labpaw** [comment]
en_US.lang will stay as is but the other .lang files will be massive (ru_RU.lang at least).
Look at ExtraTiC ru_RU.lang -> https://github.com/Glassmaker/ExtraTiC-Localization/blob/master/ru_RU.lang 3873 lines vs. 249 lines in en_US.lang. There are no problems in massive .lang files.
en_US.lang will continue use _DustName_ + "Dust", so no localization work for you. Only for me and maybe other translators.

**Comment by buttilda** [comment]
Alright then XD
I'll do it.

It will be like this:
item.aobd.dustCopper.name = Copper Dust
and so on :)

**Comment by buttilda** [comment]
Done :3

**Comment by TheVikingWarrior** [comment]
This will be fun...

**Comment by buttilda** [comment]
It's not mandatory, the old system is still in place :)
If it doesn't find any translations in the new system it will default to the old one.

**Comment by claybiockiller** [comment]
I'm a mod translator and my main working field is Chinese.
I think we need a mechanism to generate translated material name automatically because we may have a lot of ore name to translate.

**Comment by buttilda** [comment]
It can't be automatically generated because I can't edit the lang files after the mod has been compiled. And after it's been compiled I have no way of knowing which ores it will encounter.
The only way to do it is to translate the ores you know, and if any ever show up that you didn't translate send me another PR fixing it.
Unfortunately that's the only way )=

**Comment by claybiockiller** [comment]
Will this work?
metal.aobd.copper.name=Copper

**Comment by claybiockiller** [comment]
Can Regular Expression be used in localization files?

**Comment by buttilda** [comment]
Nope

**Comment by 3TUSK** [comment]
Excuse me for bothering y'all guys, but how about using `StatCollector.translatedToLocalFormatted()`?

Edit: What I mean is providing translators with individual ore name entry...

**Comment by labpaw** [comment]
You can translate the ores with individual ore names. Check [my ru_RU.lang](https://github.com/ganymedes01/Another-One-Bites-the-Dust/blob/mc1.7/src/main/resources/assets/aobd/lang/ru_RU.lang#L51). I translated as much stuff as I can find. You can just copy these strings into your .lang file and translate everything by using unlocalized names (i.e item.aobd.dustTinyFyrite.name, item.aobd.crushedPurifiedFyrite.name and etc) .

**Comment by 3TUSK** [comment]
Though it's doable, file will be too massive to complete. Perhaps I need to make a special tool to accelerate.

**Comment by claybiockiller** [comment]
I found a method to create smaller localization file and I used this method on [Chinese](https://github.com/claybiockiller/Another-One-Bites-the-Dust/blob/mc1.7/src/main/resources/assets/aobd/lang/zh_CN.lang) and [Japanese](https://github.com/claybiockiller/Another-One-Bites-the-Dust/blob/mc1.7/src/main/resources/assets/aobd/lang/ja_JP.lang) files. I think Russian file should use that way.
@Adaptivity

**Comment by labpaw** [comment]
The only method that can be used is already in use. The only way to properly translate everything is to translate each item and block name one by one. Nothing can be done here (At least for Russian localization).

**Comment by claybiockiller** [comment]
I think the largest problem is about cases. Do Russian words for metals reflex similar? @Adaptivity

**Comment by labpaw** [comment]
Not sure what you mean but in Russian I need different metal names for items/blocks. For example Ore will use its own Aluminium metal name but Cluster or Reduced Chunks will use different (while in English it's always Aluminium).

**Comment by claybiockiller** [comment]
I think using brackets will allow me use one metal name for all items/blocks for same metal. But it will lead to lacking of unity with other mods' translation.

**Comment by claybiockiller** [comment]
I think using brackets will allow me use one metal name for items/blocks. But it will lead to lacking of unity with other mods' translation.

**Comment by labpaw** [comment]
Yes, brackets can help but manually translation still better.

**Comment by 3TUSK** [comment]
@Adaptivity For "cases" he probably means [grammatical case](https://en.wikipedia.org/wiki/Grammatical_case). In Chinese there is no case changing when a noun is playing different role in sentences, so it is possible for Chinese to use something like `%ROD%CAP%WAD` only (example from thaumcraft). 
Btw I personally discourage to use brackets.
