### ISSUE TITLE
Worlds can't be loaded/created when Thermal Expansion is present

### ISSUE THREAD

**Issue by AegisLesha** [buttilda/Another-One-Bites-the-Dust#36]
After reporting the issue to either Metallurgy and CoFH Team, and as they replied they're not faulty, I report the bug here because AOBD seems to be the culprit D:

Here are the links of the reported issue
https://github.com/TeamMetallurgy/Metallurgy4/issues/58
https://github.com/CoFH/Feedback/issues/158#issuecomment-75463001

**Comment by buttilda** [comment]
That' strange... AOBD doesn't add any direct compatibility with Metallurgy, so I don't see how it could be causing the issue.

Does the crash only happen when you have all three mods installed? If you remove AOBD or Metallurgy does the crash stop?

**Comment by AegisLesha** [comment]
It doesn't
So apparently another mod is messing with TE
Here're screens of the current instance I use, who knows, might help:
http://puu.sh/gcOoB/dba70f9032.png
http://puu.sh/gcOqw/753332f383.png
http://puu.sh/gcOsE/f088747a37.png
http://puu.sh/gcOu9/b7fa748edd.png
http://puu.sh/gcOvG/665a95e556.png
http://puu.sh/gcOyk/b89ff8cfe9.png
http://puu.sh/gcOzf/313be88a8d.png

**Comment by buttilda** [comment]
Definitely not AOBD's fault as far as I'm concerned so I'm closing this for now. Feel free to ask questions or post new information on the matter if you think this is still AOBD.
