### ISSUE TITLE
I know you're aware of the issue, but Mekanism8 has new API/IMC comms system.

### ISSUE THREAD

**Issue by kotoroshinoto** [buttilda/Another-One-Bites-the-Dust#39]
the issue with AOBD was initially raised in : https://github.com/aidancbrady/Mekanism/issues/2180#issuecomment-82324572

but I figure it doesn't hurt to have an issue here for you to update us when things are functional, as the issue isn't strictly identical to the referenced issue on Mekanism's side.

**Comment by kotoroshinoto** [comment]
https://github.com/ganymedes01/Another-One-Bites-the-Dust/issues/41#issuecomment-82509540

since this issue was for the mekanism thing, Just linking this here.

**Comment by kotoroshinoto** [comment]
Here is the build failure: http://pastebin.com/fGhVsSCn
still the same as before as far as I can see.

**Comment by kotoroshinoto** [comment]
should I be building Mek version 7 by building their newest source or using the newest download from curse?

B/C the newest release for 7 is what I put in there and its not happy.

**Comment by buttilda** [comment]
I've just made another commit that might fix the problem. If that doesn't work then you'll have to wait. No point on shoehorning quick fixes anymore, I'll just re-write the whole thing to use the new IMC system that was put in place. But I can't do that until later today, so you'll need to wait a few hours.

**Comment by kotoroshinoto** [comment]
thats fine. No sense trying to work on doing it with a system that is being replaced XD

**Comment by kotoroshinoto** [comment]
I have the source pulled i'll see if I can figure anything out on my own in the meantime. Its pointless and futile, but I might learn something.

**Comment by buttilda** [comment]
This has been implemented and tested.
There is a bug on Mekanism's IMC system atm which is preventing this from working. As soon as my PR gets accepted there this will work.
