### ISSUE TITLE
[Idea] Centralize nuggets/ingots/blocks/fluid-metals as well?

### ISSUE THREAD

**Issue by kotoroshinoto** [buttilda/Another-One-Bites-the-Dust#40]
Would there be anything wrong with this in principle? Could the mod go about putting in detailed spawn rules in a specialized config file and maybe even replace the metals in other mods' recipes if their API allows for it? (so we can cut down on the multiple versions of things like steel/copper/silver that don't stack even though they're technically the same thing functionally).

If this could be done, then when using these other mods we could disable their spawn rules for their custom ores and have them use AOBD items instead, making life simpler. (doesn't AOBD allow for adding in custom dusts already or am I mis-remembering?)

**Comment by kotoroshinoto** [comment]
I do realize the idea is ambitious, but I thought of it yesterday and figured AOBD was already halfway there and wanted to see what you thought.

**Comment by buttilda** [comment]
This would be impossible to do in a nice and clean way. Some mods allow recipes overrides, some don't... AOBD is meant to be a simple and clean mod that just sits on top of the others. If I start fiddling with other mods recipes then problems start to arise.

**Comment by kotoroshinoto** [comment]
Perhaps it could be left up to things like minetweaker for mods that don't get in line, and you could provide methods for mods to opt-in to AOBD in a self-registering sort of way rather than having AOBD do the work for them. 

It might be worth a try with a less bull in chinashop approach.

**Comment by kotoroshinoto** [comment]
Never know if it'll catch on, if not putting it within AOBD itself, perhaps this idea could become a sibling mod with a similar idea. You won't know if the other mods will be accepting of it until it exists for use.

**Comment by kotoroshinoto** [comment]
maybe could have a series of methods named RegisterMetal where you provide either the ability to select a color (to recolor a default set of images in lieu of having to provide resource files), or a set of resource image files for ore/nugget/ingot/fluid and have it return the required item objects to the requesting mod to use in registering its recipes.

(would need to tailor it so alloys wouldn't need to provide ores, etc, but in principle I think that could work well, providing a way for the other mods to use this potential mod (or AOBD module if it were done that way) as a dependency rather than having AOBD override everything itself. In a sense it could be an improvement over the basic forge oredict.

**Comment by kotoroshinoto** [comment]
Hell the opt-in and self-registering idea makes quite a bit of sense for AOBD as well, is there already something like that built in?
