### ISSUE TITLE
Build failure with freshly downloaded dependency mods

### ISSUE THREAD

**Issue by kotoroshinoto** [buttilda/Another-One-Bites-the-Dust#41]
contents of libs:
appliedenergistics2-rv1-stable-1.jar
buildcraft-6.4.3.jar
BuildcraftAdditions-1.7.10-2.0.2.jar
buildcraft-compat-6.4.0.jar
CoFHCore-[1.7.10]3.0.0RC7-211.jar
EnderIO-1.7.10-2.2.8.349.jar
Eureka-1.7.10-2.2.jar
Factorization-1.7.10-0.8.88.8.8888h.jar
Ganys Nether-1.7.8.jar
HydCraft-1.7.10-2.0.87-universal.jar
industrialcraft-2-2.2.695-experimental.jar
Mantle-1.7.10-0.3.2.jar
Mekanism-1.7.10-7.1.2.186.jar
Mekanism-1.7.10-8.0.0.homebaked.jar
MekanismGenerators-1.7.10-7.1.2.186.jar
MekanismGenerators-1.7.10-8.0.0.homebaked.jar
MekanismTools-1.7.10-7.1.2.186.jar
MekanismTools-1.7.10-8.0.0.homebaked.jar
Modular Systems-1.7.10-1.7.2.jar
NetherOres-[1.7.10]2.3.0RC4-4.jar
Railcraft_1.7.10-9.5.0.0.jar
RandomAdditions Alpha 0.10 mc1.7.10.jar
steamcraft2-1.7.10-B4.1b.jar
TConstruct-1.7.10-1.8.3b.jar
Thaumcraft-1.7.10-4.2.3.5.jar
ThermalExpansion-[1.7.10]4.0.0RC7-141.jar
Ultratech-1.7.10-0.9.6.1.jar

error:
:compileJava
warning: [options] bootstrap class path not set in conjunction with -source 1.6
error: error reading /home/mgooch/mod_repos/Another-One-Bites-the-Dust/libs/NetherOres-[1.7.10]2.3.0RC4-4.jar; cannot read zip file
/home/mgooch/mod_repos/Another-One-Bites-the-Dust/build/sources/java/ganymedes01/aobd/recipes/modules/Steamcraft.java:3: error: package flaxbeard.steamcraft.tile does not exist
import flaxbeard.steamcraft.tile.TileEntitySmasher;
                                ^
/home/mgooch/mod_repos/Another-One-Bites-the-Dust/build/sources/java/ganymedes01/aobd/recipes/modules/Steamcraft.java:16: error: package TileEntitySmasher does not exist
        TileEntitySmasher.REGISTRY.registerSmashable("ore" + ore.name(), getOreStack("dust", ore));
                         ^
/home/mgooch/mod_repos/Another-One-Bites-the-Dust/build/sources/java/ganymedes01/aobd/recipes/modules/Mekanism7.java:63: error: method addChemicalInjectionChamberRecipe in class RecipeHandler cannot be applied to given types;
            RecipeHandler.addChemicalInjectionChamberRecipe(new AdvancedInput(stack, hydrogenChloride), getOreStack("shard", ore, 4));
                         ^
  required: ItemStack,String,ItemStack
  found: AdvancedInput,ItemStack
  reason: actual and formal argument lists differ in length
/home/mgooch/mod_repos/Another-One-Bites-the-Dust/build/sources/java/ganymedes01/aobd/recipes/modules/Mekanism7.java:64: error: method addChemicalInjectionChamberRecipe in class RecipeHandler cannot be applied to given types;
        RecipeHandler.addChemicalInjectionChamberRecipe(new AdvancedInput(getOreStack("crystal", ore), hydrogenChloride), getOreStack("shard", ore));
                     ^
  required: ItemStack,String,ItemStack
  found: AdvancedInput,ItemStack
  reason: actual and formal argument lists differ in length
4 errors
1 warning
:compileJava FAILED

**Comment by kotoroshinoto** [comment]
I re-jarred Nether ores manually, to side step the problem there.
Still looking into the Steamcraft/mekanism problems

**Comment by kotoroshinoto** [comment]
looks like I downloaded the wrong steamcraft XD

**Comment by kotoroshinoto** [comment]
Mek problem seems to a be a signature mismatch, not entirely familiar with the codebase but I'll see if I can come to understand the problem.

**Comment by buttilda** [comment]
Also, I haven't tested the changes implemented to support both mekanism 7 and 8 simultaneously.
So that could also be causing a crash...

**Comment by kotoroshinoto** [comment]
It might be using the classes from the wrong version you mean?

**Comment by buttilda** [comment]
I think I've found the problem. Give me a minute :3

I'll close this as it's not really an issue (even the building is not working atm, there's already another open issue referencing this problem)

**Comment by kotoroshinoto** [comment]
wasn't the other open thing the thread on the pull request?

**Comment by kotoroshinoto** [comment]
oh you meant the one specific for mek that I made XD

**Comment by buttilda** [comment]
Hm, there's a problem, the version of Mekanism on the repo is still marked as 7.1.2 despite it being version 8.
That's why AOBD is getting confused.

Edit: Nvm, I'm a derp. Was building the wrong branch XD
Try redownloading the AOBD source, it should work now.

**Comment by kotoroshinoto** [comment]
Do i have to reclone or would a pull be enough?

**Comment by buttilda** [comment]
a PR should suffice :3
