### ISSUE TITLE
Crash with the new mekanism

### ISSUE THREAD

**Issue by crunkazcanbe** [buttilda/Another-One-Bites-the-Dust#45]
I crashed with the new mekanism http://pastebin.com/dN1vfWRJ

I will go back to the old mekanism until you can update this .

Thank you

-Crunk

**Comment by buttilda** [comment]
It's already fixed. I'll release the update soon :3

**Comment by buttilda** [comment]
Download the new version here: http://minecraft.curseforge.com/mc-mods/221863-another-one-bites-the-dust
