### ISSUE TITLE
Class not found 2.5.0

### ISSUE THREAD

**Issue by MakerTim** [buttilda/Another-One-Bites-the-Dust#49]
Just installed your mod, 
and got a lot of crashes,
http://pastebin.com/Rsryb5zH

**Comment by buttilda** [comment]
Try re-downloading the mod

**Comment by buttilda** [comment]
It was an issue with FML/Forge, it wasn't AOBD's fault afaik.
Either the jar you got is corrupted or the version of FML you have is bugged.

**Comment by MakerTim** [comment]
Fixed, my filezilla is bugged... sorry for bothering you
Keep up the great work!

**Comment by buttilda** [comment]
No problem! Thanks for taking your time to report a possible issue :)
