### ISSUE TITLE
Support for tinkers oreberry bushes

### ISSUE THREAD

**Issue by zlepper** [buttilda/Another-One-Bites-the-Dust#51]
Hello. 
Would it be possible to add support for tinker's constructs oreberry bushes?

I know there are bound to be some issues since they are worldgen and not something you can craft, and some people would likely call it overpowered. That is why it would be nice if they are off-by-default, so modpack makers and others would have to enable them and add them to worldgen, eg. by using CoFH.

If it is out of the scope of this mod, could it perhaps be a seperate mod? I just thought it would make sense in AOBD since it already has all the structure in place for finding ores, ingots and such?

**Comment by buttilda** [comment]
You mean automatically creating ore berries for every single ore?

**Comment by zlepper** [comment]
Exactly that, though without 5 different tin ore berries

**Comment by buttilda** [comment]
The only problem I have with this is the balance issues.
And making it but leaving it off by default will result in 90% of people not even knowing it's there.
I do like the idea though...

Perhaps an add-on to AOBD. What do you think?

**Comment by zlepper** [comment]
I'm all for that

**Comment by buttilda** [comment]
I haven't worked on it in a while (due to personal stuff going on) but it's being developed here: https://github.com/ganymedes01/Another-One-Bites-The-Dust-Berry-Bushes

Release shouldn't take long, most of the work is done.
