### ISSUE TITLE
Support request for draconium ore.

### ISSUE THREAD

**Issue by TimB1087** [buttilda/Another-One-Bites-the-Dust#52]
I would like to see support for Draconic Evolution's draconium ore. Simple nuff. =)

**Comment by ganymedes01** [comment]
Does it have an ore and an ingot?

**Comment by buttilda** [comment]
AOBD will automatically support it if:
-It has an ore and ingot
-Both ore and ingot are registered in the ore dictionary under the same name (oreDraconium and ingotDraconium I presume)

If any ore fails to match any or both of those criteria AOBD will not support it.

**Comment by TimB1087** [comment]
Ah, ok. I will direct this to Draconic Evolution, then. There is no ore dictionary for their ores or ingots.

**Comment by buttilda** [comment]
I just looked at their GitHub page and it looks like they've added the ore dictionary registering in their latest version. So try that one, if not, it's already implemented in there, so just wait until their next update :)

**Comment by TimB1087** [comment]
Yea, I noticed. We are pushing the update as we speak. 

Although, he doesn't like the fact that AOBD allows you to quintuple draconic ore through Mekanism, because draconic ingots are crafted by surrounding draconic dust around an iron ingot. A weird recipe, I know. Not your fault, though.

I'm going to keep in touch with the dev and see if I can throw him suggestions to find some middle ground to continue allowing cross mod support with his stuff through AOBD, but keep it true to his design intent. He's already aware that AOBD is doing this, but I informed him that he can try treating his ore like redstone ore rather than an ingot-making-ore, since the ore yields dust, not ingots.

Anywho, great mods you have! Keep up the great work!

**Comment by buttilda** [comment]
Yeah there is potential for unbalancing certain mods using AOBD. Not much that can be done unfortunately.
Some people will say that being able to process cobalt/ardite with mekanism would also be unbalanced, some people would say it's fair... Mod authors can say "hey this ore is meant to be rare" but if users want to change that then it should be up to them (after all, that's what minecraft is about: everyone has the experience they want to have). There are plenty of mods that allow adding recipes and changing world gen, so it's not just AOBD that has the potential or changing his balance :3
