### ISSUE TITLE
[Support Request]: Please Add Support For Buildcraft Additions :)

### ISSUE THREAD

**Issue by Lanse505** [buttilda/Another-One-Bites-the-Dust#54]
Please Add Support For Buildcraft Additions :)

Also 

Hiya Gany o/ :D

**Comment by buttilda** [comment]
Hello:3
Support gor BCA is already in, not sure if I've released the version with it in yet though (holliday brain doesn't work well)

**Comment by Lanse505** [comment]
Haha :P okey then, I need Mah BCA Fix Man <3 ;)
