### ISSUE TITLE
Move AOBD's Thaumonomicon tab 

### ISSUE THREAD

**Issue by labpaw** [buttilda/Another-One-Bites-the-Dust#59]
AOBD adds just one entry and whole new tab to Thaumonomicon but the number of tabs "limited". Is it possible to move AOBD tab to some Thaumcraft tab? More info [here](https://github.com/CovertJaguar/Railcraft/issues/565)

**Comment by labpaw** [comment]
Also, Mekanism gases seems to not support individual names. I tried _gas.aobd.cleanFyrite_ and _gas.aobd.dirtyFyrite_ templates. I'm doing this wrong or what?

**Comment by buttilda** [comment]
I probably forgot to add the custom names support to the gases. I'll fix that when I'm back at my laptop.

As for the Thaumonomicon tab... Nothing I can do about it. The Thaumcraft API says that each mod should add it's own tab...
