### ISSUE TITLE
Crash on Forge 1401

### ISSUE THREAD

**Issue by bochen415** [buttilda/Another-One-Bites-the-Dust#65]
I almost certainly did something stupid. 
I'm crashing with only aobd and the addon with multimc and also with the vanilla launcher.

aobdbb{1.0.1}
aobd{2.6.1}
Forge{10.13.3.1401}

http://paste.ubuntu.com/11052426/

**Comment by buttilda** [comment]
Unfortunately I'm the one who did something wrong =P
Thanks for reporting! I've fixed the issue already.

**Comment by bochen415** [comment]
Btw. I added the berry bushes addon to NotEnoughMods. I hope you don't mind

**Comment by buttilda** [comment]
Not at all :)
