### ISSUE TITLE
v2.6.1 not quiet fixed, crash involving AOBD and Mekanism

### ISSUE THREAD

**Issue by ChaosXten** [buttilda/Another-One-Bites-the-Dust#66]
I have a custom modpack and while going through the updates on all the mods, I noticed while testing that the game crashes when I am in creative and I click the search items tab.

I have updated Forge to 1388, and will continue to test as I update all the rest of the mods, but wanted to pass this along in case it's a bug.

I thought this was an issue with Mekanism, but after looking at the changelog for AOBD, it's possible there's still something causing trouble.

Here are the crash logs ...

latest.log - http://pastebin.com/9TgZeUib
crash log - http://pastebin.com/ixuzT0ZZ

... PopsRocker

**Comment by buttilda** [comment]
Yeah someone reported that earlier. It's been fixed for 2.6.2 which I'll release in a bit :)
Sorry about that...

**Comment by ChaosXten** [comment]
No worries, I appreciate the quick update, thank you !!
