### ISSUE TITLE
isn't this caused from aobd right?

### ISSUE THREAD

**Issue by lightning02** [buttilda/Another-One-Bites-the-Dust#67]
I tryed to put in server startup aobd and it crashed. I'm not very smart at read crash reports, I just wanted to figured out for sure it was some other mod. (don't take me bad, I'm a bit noob sometime :D)

---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 10/05/15 9.57
Description: Exception in server tick loop

cpw.mods.fml.common.MissingModsException
    at cpw.mods.fml.common.Loader.sortModList(Loader.java:244)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:472)
    at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:87)
    at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:319)
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:170)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:620)
    at java.lang.Thread.run(Unknown Source)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.8.0_40, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 362608896 bytes (345 MB) / 897056768 bytes (855 MB) up to 1908932608 bytes (1820 MB)
    JVM Flags: 2 total; -XX:PermSize=2G -XX:MaxPermSize=3G
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: ~~ERROR~~ NullPointerException: null
    Profiler Position: N/A (disabled)
    Is Modded: Definitely; Server brand changed to 'cauldron,craftbukkit,mcpc,fml,forge'
    Type: Dedicated Server (map_server.txt)

**Comment by buttilda** [comment]
You probably added AOBDBB and not AOBD.
The log is saying you have a missing mod.
AOBD is standalone
AOBDBB depends on AOBD

**Comment by lightning02** [comment]
I've add the AOBD version 2.6.2.
I've updating Calduron and i've solved the problem! Ty anyway :)

**Comment by buttilda** [comment]
np :3
