### ISSUE TITLE
Add the ability to disable blocks crafted from materials

### ISSUE THREAD

**Issue by Xen1290** [buttilda/Another-One-Bites-the-Dust#68]
For example, the ability to disable Meteorite Block.
Thanks @ganymedes01 , very good mod! Keep it up!

**Comment by buttilda** [comment]
Thank you :)
But...
What do you mean? You can already turn off specific materials in the config file...

**Comment by Xen1290** [comment]
Sorry, my english is bad. I hope you understand now.
I have a material, Meteorite(From FallingMeteors), where is registered only the ingot with "ingotMeteorite", and the block(Meteorite Block) exists but does not have the oredictionary.
With adding aobd, it added another meteorite block, so I looked in the config option to disable ONLY the registration of the block, but there isn't this configuration.
I added the oredictionary to block via minetweaker(blockMeteorite) to prevent the aodb registration, but that did not change the things.
![a](https://cloud.githubusercontent.com/assets/8685029/7666924/a4518d16-fbf7-11e4-99ff-1da54776dec9.png)
![aaa](https://cloud.githubusercontent.com/assets/8685029/7666923/a45079ee-fbf7-11e4-8b1f-46a92635fd37.png)

Some screenshot

**Comment by Xee1** [comment]
![a](https://cloud.githubusercontent.com/assets/8685029/7666919/2ffd4cac-fbf7-11e4-962e-3a4373041c54.png)
![aaa](https://cloud.githubusercontent.com/assets/8685029/7666920/3002cf2e-fbf7-11e4-9b6f-221c779d0775.png)
Some screenshot

**Comment by buttilda** [comment]
oh right! I get what you mean now :)

Yeah mods that allow users to register blocks in the OreDictionary tend to do it too late, so AOBD doesn't pick it up.

Any chance the author of Falling Methors can register his block in the OreDictionary? Would make things a lot easier XD I'll see if I can speak to him/her directly. Hopefully the mod is open source...

**Comment by buttilda** [comment]
Done. Sent him a request to change it.
I'll wait a couple of days and if he doesn't pull it then I'll fix it on my side :)

**Comment by buttilda** [comment]
I'll leave this open otherwise I'll forget lol

**Comment by Xen1290** [comment]
Thanks!

**Comment by buttilda** [comment]
Author's merged my PR, so on his next update this will be fixed :)

**Comment by Xen1290** [comment]
Thanks!
