### ISSUE TITLE
Newest version as of today on curse I got a crash

### ISSUE THREAD

**Issue by crunkazcanbe** [buttilda/Another-One-Bites-the-Dust#69]
The crash happens when I click on the tab in creative that shows all the items . Vanillas regular way of searching for things . As soon as I click it game freezes for a bit then crashes . Crash log here http://pastebin.com/tRk6FTXk

**Comment by buttilda** [comment]
That has been fixed in the latest version of AOBD. Just update and you should be fine :)

**Comment by buttilda** [comment]
Are you sure you're running 2.6.2?
I just loaded it along with the latest Mekanism 8 (from its website) and there were no crashes when searching for things on the creative menu.

**Comment by crunkazcanbe** [comment]
I am almost positive it is 2.6.2 . Although i am running latest dev build of MEK on Jenkins that fixed a couple issues . I am at work now night shift ,but when i get home i will check everything including running it with the release version on MEK site.
