### ISSUE TITLE
Where is the changelog.txt?

### ISSUE THREAD

**Issue by chaos234** [buttilda/Another-One-Bites-the-Dust#71]
Hi,

I'm playing on a 1.5.0 FTB Infinity Server with AOBD 2.5.0 now I've seen that a newer Version is out but I can't found anything about the changes which where made.

Can you pls add a changelog.txt or smth similar?

**Comment by buttilda** [comment]
You can see the changelog on the same website where the files are hosted!
Here's 2.6.0 http://minecraft.curseforge.com/mc-mods/221863-another-one-bites-the-dust/files/2236088
You can navigate through the [file list](http://minecraft.curseforge.com/mc-mods/221863-another-one-bites-the-dust/files) and just click on whatever file you want to see the changelog for :)
