### ISSUE TITLE
[2.7.0] Server Crash on startup

### ISSUE THREAD

**Issue by Xiaminou** [buttilda/Another-One-Bites-the-Dust#76]
Forge: 1448
AOBD: 2.7.0
Crash Report: http://pastebin.com/rkYyFe5T

server is looking for " Forge : [10.13.4.1448,)" mod for some reason.

Note: Client works fine

**Comment by Xen1290** [comment]
Your server is running Forge 10.13.3.1403, AOBD need Forge 10.13.4.1448 (Recommended Version)

**Comment by Xiaminou** [comment]
wait what, it shouldn't be.

Edit: Looks like you're right, it says that, but that doesn't make any sense I've  been running this for weeks with 1448 and suddenly it decides it's 1403, weird.
Okay well sorry for that, nevermind that crash report. still don't understand how it switched back to 1403 and how I was able to connected to 1403 with 1448 yesterday, but okay, minecraft I guess.

**Comment by buttilda** [comment]
Is it still crashing after you updated forge?

**Comment by Xiaminou** [comment]
no

**Comment by buttilda** [comment]
Awesome :3
