### ISSUE TITLE
Client crash while looking up recipes for clusters in Thaumonomicon

### ISSUE THREAD

**Issue by TheOnlyRupert** [buttilda/Another-One-Bites-the-Dust#78]
I have the latest version (2.7.1) for minecraft 1.7.10
When I get to around the third for forth page of the AOBD tab in Thaumcraft's Thaumonomicon, the client crashes. Server Unaffected.

Crash Log: http://pastebin.com/iBPWUe23

**Comment by buttilda** [comment]
No idea what could be causing it.
Report this to Thaumcraft's author, I don't really know what's causing the crash, maybe he'll know what the problem it
