### ISSUE TITLE
Nuggets are unusable.

### ISSUE THREAD

**Issue by anishin** [buttilda/Another-One-Bites-the-Dust#80]
Hello.
Firstly, thank you very much for your work!
Secondly, I found strange bug in AOBD (v. 2.7.0-2.7.1).
There are no recipes to craft nuggets from ingots and back. I can obtain nuggets only using Magic Bees and TConstruct. And I can get ingots only using smeltery from TConstruct.
This issue affects the following metals:
- Osmium (Mekanism 8.1.5.246 is installed),
- Uranium (IC2 and Advanced Solar Panels are installed on my modpack).
- Iridium (IC2 and Advanced Solars are installed)
- Yellorium (latest version or BigReactors is installed).
  Perhaps there are any metals, which I don't listed there.

Please, fix this problem - add recipes to craft ingots from nuggets and vice versa.
Thank you for your work again!

P. S. Sorry for my English. I'm from Russia.

**Comment by buttilda** [comment]
Oversight on my part, thanks for letting me know.
I'll be fixing it soon :)
