### ISSUE TITLE
Advent of Ascension Support

### ISSUE THREAD

**Issue by Shadows-of-Fire** [buttilda/Another-One-Bites-the-Dust#82]
Well, title says it all, Just asking if it is possible, especially since the mod has shown more and more popularity within the community, the ability for its ores to be processed would be extremely useful.

**Comment by buttilda** [comment]
If it's ores aren't processable then it's either because the author isn't registering them in the OreDictionary or because or they aren't registering them early enough

**Comment by buttilda** [comment]
Nothing I can do about it unfortunately.
You're going to have to contact the author and tell him/her to fix it.

You can link them to this thread if you'd like.
