### ISSUE TITLE
Remove UltraTech module

### ISSUE THREAD

**Issue by labpaw** [buttilda/Another-One-Bites-the-Dust#84]
[Mod is dead, no reason to keep it I guess?](http://minecraft.curseforge.com/mc-mods/70036-ultratech)
cout970:
_The project is abandoned. 
Currently I'm working in a new mod called Magneticraft._
You might want to support Magneticraft but I'm not sure (I haven't checked this yet) if it adds any ore processing.

**Comment by buttilda** [comment]
I'll just remove UltraCraft then :3
