### ISSUE TITLE
pointless blocks and Draconic Evolution Book crash

### ISSUE THREAD

**Issue by SuperSandro2000** [buttilda/Another-One-Bites-the-Dust#85]
Why do you need to add Draconium, lithium and prometheum blocks? Draconic Evolution has already draconium blocks and the other ones are added by Gemblocks for greg.
The missing draconium block crashes the game if you look up the draconium ingot entry in draconic evoltuion book.

**Comment by buttilda** [comment]
That's because the blocks added by thkse mods aren't registered in the OreDictionary, not my faul if AOBD then assumes they aren't present
