### ISSUE TITLE
Using an outdated api from Magneticraft

### ISSUE THREAD

**Issue by cout970** [buttilda/Another-One-Bites-the-Dust#88]
In the last release of Magneticraft the ore procesing system and the api changed, so this mod make the game crashes when Magneticraft is installed because uses the old api, this is the crash log: http://pastebin.com/nQYe14tM , This is the api repository this the updated version: https://github.com/cout970/Magneticraft-API-and-Insues

**Comment by buttilda** [comment]
You can turn the Magictaft support off in the config file for the time being. I'll update the API

**Comment by Dulciphi** [comment]
ya, I did turned off the Magneticraft support, then got an error for yellorium. Pardon my noobity if the problem's at my end.
[02:30:12] [Client thread/ERROR] [FML/]: The fluid registry is corrupted. A fluid ganymedes01.aobd.recipes.RecipesModule$MoltenMetal aobdyellorium is not properly registered. The mod that registered this is broken
http://pastebin.com/0jh23Dcn

**Comment by buttilda** [comment]
Forge always has such helpful error logs... it doesn't bother to say what I'm doing wrong, and it's not like asking them gets you anywhere >_> I'll see what I can do.

Edit: Fixed the fluid problem :3 I hope...

**Comment by buttilda** [comment]
Hey @cout970, I've updated my dependency to 0.3.3 that I downloaded form CurseForge and I don't see any errors in my dev environment, what's going on? lol

**Comment by cout970** [comment]
In the new api the crusher recipe needs the probability in floats (0 - 1) (like the grinder recipe) instead ints (0 - 100), also the new version have chunks, pebbles, rubbles instead of gravel and sand.

**Comment by buttilda** [comment]
Is that version up for download already?

**Comment by cout970** [comment]
Alll this changes should be in the version 0.3.3, what is the problem?

**Comment by buttilda** [comment]
My compiler didn't complain about anything, but I guess it wouldn't because your changes wouldn't cause any errors to be thrown.
