### ISSUE TITLE
2.8.0 The fluid registry is corrupted

### ISSUE THREAD

**Issue by SvEgiiVEteR** [buttilda/Another-One-Bites-the-Dust#89]
http://paste.ubuntu.com/12002954/
crash the server after loading World

part of the server logs. 9 line
http://paste.ubuntu.com/12002997/

**Comment by buttilda** [comment]
Reported earlier and already fixed.
Thanks anyway :)

**Comment by SvEgiiVEteR** [comment]
and thank you so quickly. waiting for an update)

**Comment by buttilda** [comment]
It's been released. 2.8.1 is already on CurseForge.
Could you let me know if it actually fixed the issue? (I wasn't able to reproduce it on my system, so that fix was a bit of a blind one)

**Comment by SvEgiiVEteR** [comment]
Yes! Server has started)) now I'll try to go to the server

UP
all is well, I gone to the server)
