### ISSUE TITLE
[Request] Ex Nihilo/Ex Astris Compat

### ISSUE THREAD

**Issue by claybiockiller** [buttilda/Another-One-Bites-the-Dust#92]
Greetings.

Ex Nihilo introduced a special ore processing method:

Tier1:Use hammer smash ores into broken ores, craft broken ores into ore gravels, smelt ore gravels into ingots.

Tier2:Smash ore gravels into crushed ores, craft crushed ores into ore sands, smelt ore sands into ingots.

Tier3:Smash ore sands into powered ores, craft powered ores into ore dusts, smelt ore dusts into ingots.

On the other hand, Ex Nihilo and Ex Astris Rebirth offered a alternative way to get metal:

Sifting gravels/sands/dusts for overworld ores,crushed netherrack for nether ores, crushed endstone for end ores, and stone for ore berries.

As a ore processing enhancing mod, AOBD and AOBD Ore Berries can use Ex Nihilo API. And I think the only problem  is how to config sifting process.

Clayblock

**Comment by buttilda** [comment]
Started work on it today :)

**Comment by buttilda** [comment]
Done :3
