### ISSUE TITLE
[Request] Add Plates for Registered Metals

### ISSUE THREAD

**Issue by UndeadZeratul** [buttilda/Another-One-Bites-the-Dust#94]
Would it be possible to add plates for each metal registered?  I know of at least a few different mods that implement some form of plate, including Railcraft, IC2/GT, and even Flaxbeard's Steam Power.

The only problem with this, though, is that unlike the rest which make plates equal to ingots, FSP has their plates equal to 2/3 of an ingot (2 ingots of a given metal tossed into their crucible will end up giving back 3 plates), which means it might be tricky (or not if you register two versions) to figure out what the different versions of the plates will end up being worth in the end.

Personally I'd appreciate seeing this because I play with FSP, but considering many different mods utilize metal plates instead of ingots, I think it'd just be nice to add plates for additional compatibility between mods and/or as tweaking resources for pack developers.

**Comment by buttilda** [comment]
It's not really in AOBD's scope to just add seemingly random items like that.
It's meant to just make ores processable by every ore-processing mod out there.

There are mods out there that can help you with adding simple cosmetic items (like plates), so I'd recommend you use those :)

**Comment by UndeadZeratul** [comment]
Aww darn, worth a shot; thanks though.  I have an idea for a custom item I can implement using something like ResourceLoader or similar, and the AOBD custom configuration, since I just have to include the texture and overlay images, and have them match up appropriately, right?

**Comment by AegisLesha** [comment]
On a side note, if I may necropost this request:
Plates might be considered as, more or less, ore processing in some mods.
