### ISSUE TITLE
Rotarycraft extractor server crash with AOB

### ISSUE THREAD

**Issue by Saereth** [buttilda/Another-One-Bites-the-Dust#97]
Crashlog: http://pastebin.com/ey9byubT

Reported to Reika first and he says its an aobd issue:
https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/235

version 2.8.2 aob, latest version of all reikas mods as of today

**Comment by buttilda** [comment]
It's caused due to BigReactors making a mess of their OreDictionary registering.
But I've added a workaround for it into AOBD. I'll get a release out soon :)
