### ISSUE TITLE
Another RotaryCraft / AOBD mishandling

### ISSUE THREAD

**Issue by TotalHamman** [buttilda/Another-One-Bites-the-Dust#98]
Looks like Factorization Dark Iron is also having the same issue as Big Reactors / Uranium that was just fixed.

http://pastebin.com/Kk1Dnd1w

**Comment by TotalHamman** [comment]
Disabling RotaryCraft integration on the DarkIron entry resolved the crash as well.

**Comment by buttilda** [comment]
probably due to the way it is registered in the ore dictionary (darkIronFz instead of just darkIron) caused the filter to miss it.
Sorry about that!
