### ISSUE TITLE
Conflict with Magneticraft

### ISSUE THREAD

**Issue by firespark81** [buttilda/Another-One-Bites-the-Dust#99]
I have to disable everything Magneticraft in the AODB config and it works. If I do not I get a crash. Here is the log file. Hope this helps. http://pastebin.com/3ACdXPPi

**Comment by buttilda** [comment]
It was due to a recent change in its API. I've fixed it. There should be a release later today :)

**Comment by buttilda** [comment]
v2.8.4 is out and contains the fix.

**Comment by firespark81** [comment]
Awesome! Great job and fantastic mod! Thank you for the quick fix.
